version: '3.1'

networks:
  default:

services:
  web:
    container_name: web
    environment:
      - REACT_APP_API_URL=http://localhost:3333
    networks:
      - default
    build:
      context: client
      target: development
    volumes:
      - ./client:/usr/src/app
    command: npm start
    ports:
      - 3000:3000
  seed:
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=D3v_P4ss_S3CuR3
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_USER=root
      - MONGO_PASS=mongopass
    networks:
      - default
    build:
      context: server
      target: development
    command: npm run seed
  api:
    container_name: api
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=D3v_P4ss_S3CuR3
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_USER=root
      - MONGO_PASS=mongopass
    networks:
      - default
    build:
      context: server
      target: development
    volumes:
      - ./server:/usr/src/app
    command: npm run dev
    ports:
      - 3333:3333
  
  worker:
    container_name: worker
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=D3v_P4ss_S3CuR3
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_USER=root
      - MONGO_PASS=mongopass
    networks:
      - default
    build:
      context: server
      target: development
    volumes:
      - ./server:/usr/src/app
    command: npm run dev:worker
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopass
    ports:
      - "27017:27017"
    volumes:
      - ./tmp/data:/data/db
    networks:
      - default
  redis:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass D3v_P4ss_S3CuR3



      